<script lang="ts">
	import ProjectCard from "$lib/ProjectCard.svelte";
	import type { Project } from "$lib/ProjectCard";

	const projects: Project[] = [
		{
			title: 'fernando.is',
			description: 'This is so meta',
			url: 'https://fernando.is',
			repo: 'https://github.com/fmaclen/fernando.is',
      theme: 'fernando-is'
		},
    {
      title: 'Canutin',
      description: 'A personal finance desktop application',
      url: 'https://canutin.com',
      repo: 'https://github.com/fmaclen/canutin-desktop',
      theme: 'canutin'
		},
    {
      title: 'svelte-currency-input',
      description: 'A form input that converts numbers to localized currency formats as you type',
      url: 'https://www.npmjs.com/package/@canutin/svelte-currency-input',
      repo: 'https://github.com/fmaclen/svelte-currency-input',
      theme: 'svelte-currency-input'
		},
    {
      title: 'Julia Sanfrancisco',
      description: 'A web-based detective game largely generated by AI',
      url: 'https://julia.strictoaster.com',
      repo: 'https://github.com/fmaclen/julia-sanfrancisco',
      theme: 'julia-sanfrancisco'
    },
    {
      title: 'auto-garden',
      description: 'Computers that garden for you',
      url: '',
      repo: '',
      theme: 'auto-garden'
    },
    {
      title: 'Promptspree',
      description: 'Chat-based AI article generator and editor',
      url: '',
      repo: '',
      theme: 'promptspree'
    },
    {
      title: 'rule-of-three',
      description: 'A tiny direct proportion calculator for macOS',
      url: '',
      repo: '',
      theme: 'rule-of-three'
    }
	];
</script>

<ul class="ul">
  {#each projects as project}
    <li class="ul__li">
      <ProjectCard {project} />
    </li>
  {/each}
</ul>

<style lang="scss">
  ul.ul {
    position: relative;
    column-count: 2;
    column-gap: 16px;
    list-style: none;
    margin-block: unset;
    padding: 64px;
    max-width: 1280px;
    margin-inline: auto;

    &::before {
      content: '';
      position: absolute;
      top: 0;
      left: 50%;
      height: 100dvh;
      width: calc(50% - 32px);
      transform: translateX(-50%);
      border-left: 1px solid hsl(0, 0%, 20%);
      border-right: 1px solid hsl(0, 0%, 20%);
      z-index: -1;
    }

    @media (max-width: 1280px) {
      column-count: 1;
      max-width: 640px;

      &::before {
        width: unset;
        border-right: unset;
      }
    }
  }

  li.ul__li {
    display: inline-block;
    width: 100%;
    margin-bottom: 16px;
  }
</style>
