<script lang="ts">
	const projects = [
		{
			title: 'fernando.is',
			description: 'This is so meta',
			url: 'https://fernando.is',
			repo: 'https://github.com/fmaclen/fernando.is'
		},
    {
      title: 'Canutin',
      description: 'A personal finance desktop application',
      url: 'https://canutin.com',
      repo: 'https://github.com/fmaclen/canutin-desktop'
		},
    {
      title: 'svelte-currency-input',
      description: 'A form input that converts numbers to localized currency formats as you type',
      url: 'https://www.npmjs.com/package/@canutin/svelte-currency-input',
      repo: 'https://github.com/fmaclen/svelte-currency-input'
		},
    {
      title: 'Julia Sanfrancisco',
      description: 'A web-based detective game largely generated by AI',
      url: 'https://julia.strictoaster.com',
      repo: 'https://github.com/fmaclen/julia-sanfrancisco'
    }
	];
</script>

<ul class="ul">
  {#each projects as project}
    <li class="ul__li">
      {project.title}
      <br>
      {project.description}
    </li>
  {/each}
</ul>

<style lang="scss">
  ul.ul {
    display: flex;
    flex-wrap: wrap;
    column-count: 4;
    column-gap: 16px;
    row-gap: 16px;
    list-style: none;
  }

  li.ul__li {
    border-radius: 4px;
    padding: 24px;
    background-color: hsl(0, 0%, 10%);
  }
</style>
