import { browser } from '$app/environment';

export interface Project {
	title: string;
	description: string;
	url: string;
	repo?: string;
	updatedAt?: string;
	theme?: string;
	images?: string[];
}

const GITHUB_API_BASE_URL = 'https://api.github.com/repos';
const LOCAL_STORAGE_LAST_CHECK_KEY = 'fernando.is-lastCheck';
const LOCAL_STORAGE_PROJECTS_KEY = 'fernando.is-projects';
const ONE_HOUR_IN_MS = 60 * 60 * 1000;
const CURRENT_REPO = 'fmaclen/fernando.is';

const baseProjects: Project[] = [
	{
		title: "The Merchant Discoverers' Company",
		description: 'Medalists and engravers specializing in custom insignia and heraldic work',
		url: 'https://merchantdiscoverers.com',
		updatedAt: '2025-12-06T00:00:00Z',
		theme: 'merchant-discoverers',
		images: [
			'merchant-discoverers-homepage.png',
			'merchant-discoverers-insignia.png',
			'merchant-discoverers-atelier.png',
			'merchant-discoverers-arms.png',
			'merchant-discoverers-engravings.png'
		]
	},
	{
		title: 'Chromabox',
		description: 'A color palette generator for designers and developers',
		url: 'https://chromabox.fernando.is',
		repo: 'fmaclen/chromabox',
		theme: 'chromabox',
		images: ['chromabox-app.png', 'chromabox-website.png']
	},
	{
		title: 'fernando.is',
		description: 'This very website',
		url: 'https://fernando.is',
		repo: 'fmaclen/fernando.is',
		theme: 'fernando-is'
	},
	{
		title: 'Hollama',
		description: 'A minimal web-UI for talking to Ollama servers',
		url: 'https://hollama.fernando.is',
		repo: 'fmaclen/hollama',
		theme: 'hollama',
		images: ['hollama-session.png', 'hollama-settings.png', 'hollama-session-new.png']
	},
	{
		title: 'Canutin',
		description: 'A personal finance application for macOS, Windows & Linux',
		url: 'https://canutin.com',
		repo: 'fmaclen/canutin-desktop',
		theme: 'canutin',
		images: [
			'canutin-dashboard.png',
			'canutin-balance-sheet.png',
			'canutin-data.png',
			'canutin-trends.png',
			'canutin-transactions.png',
			'canutin-dashboard-dark.png'
		]
	},
	{
		title: 'svelte-currency-input',
		description:
			'A masked form input that converts numbers to localized currency formats as you type',
		url: 'https://npmjs.com/package/@canutin/svelte-currency-input',
		repo: 'fmaclen/svelte-currency-input',
		theme: 'svelte-currency-input'
	},
	{
		title: 'Julia Sanfrancisco',
		description: 'A web-based detective game largely generated by AI',
		url: 'https://julia.fernando.is',
		repo: 'fmaclen/julia-sanfrancisco',
		theme: 'julia-sanfrancisco',
		images: [
			'julia-sanfrancisco-splash.png',
			'julia-sanfrancisco-montreal.png',
			'julia-sanfrancisco-street-merchant.png',
			'julia-sanfrancisco-messenger.png',
			'julia-sanfrancisco-rome.png',
			'julia-sanfrancisco-singapore.png',
			'julia-sanfrancisco-baghdad.png',
			'julia-sanfrancisco-paris.png',
			'julia-sanfrancisco-stevedore.png',
			'julia-sanfrancisco-house-detective.png',
			'julia-sanfrancisco-headquarters.png'
		]
	},
	{
		title: 'auto-garden',
		description: 'Moisture monitor and irrigation system for my plants',
		url: 'https://github.com/fmaclen/auto-garden',
		repo: 'fmaclen/auto-garden',
		theme: 'auto-garden'
	},
	{
		title: 'Promptspree',
		description: 'Chat-based AI article generator and editor',
		url: 'https://promptspree.com',
		repo: 'fmaclen/promptspree',
		theme: 'promptspree',
		images: [
			'promptspree-homepage.png',
			'promptspree-article.png',
			'promptspree-footer.png',
			'promptspree-chat.png',
			'promptspree-completion.png'
		]
	},
	{
		title: 'rule-of-three',
		description: 'A tiny direct proportion calculator for macOS',
		url: 'https://github.com/fmaclen/rule-of-three',
		repo: 'fmaclen/rule-of-three',
		theme: 'rule-of-three',
		images: ['rule-of-three-default.png']
	},
	{
		title: 'Oak Hall',
		description: 'A historic family-run estate located in Northport, Maine',
		url: 'https://oakhallestate.org/',
		updatedAt: '2021-08-06T00:00:00Z',
		theme: 'oak-hall',
		images: [
			'oak-hall-cover.png',
			'oak-hall-library.png',
			'oak-hall-gardens.png',
			'oak-hall-footer.png'
		]
	},
	{
		title: 'Pantai.io',
		description:
			'Artificial intelligence applied to the creation of tools that improve the machine-human interface',
		url: 'https://pantai.io/',
		updatedAt: '2024-01-17T00:00:00Z',
		theme: 'pantai',
		images: ['pantai-homepage.png', 'pantai-legal.png', 'pantai-careers.png', 'pantai-about.png']
	},
	{
		title: 'Palfrey Press',
		description:
			'A specialist publisher producing authoritative books on obscure historical subjects, heraldry, oral histories, & other antiquarian matters',
		url: 'https://palfreypress.com',
		updatedAt: '2024-11-13T00:00:00Z',
		theme: 'palfrey-press',
		images: [
			'palfrey-press-homepage.png',
			'palfrey-press-about.png',
			'palfrey-press-card-3.png',
			'palfrey-press-card-1.png',
			'palfrey-press-card-2.png',
			'palfrey-press-card-4.png',
			'palfrey-press-catalog.png'
		]
	}
];

function sortProjects(projects: Project[]): Project[] {
	return [...projects].sort((a, b) => {
		if (a.repo === CURRENT_REPO) return 1;
		if (b.repo === CURRENT_REPO) return -1;
		if (!a.updatedAt) return 1;
		if (!b.updatedAt) return -1;
		return new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime();
	});
}

async function fetchProjectUpdate(project: Project): Promise<Project> {
	if (!project.repo) return project;

	try {
		const response = await fetch(`${GITHUB_API_BASE_URL}/${project.repo}`);
		if (!response.ok) return project;

		const data = await response.json();
		return {
			...project,
			updatedAt: data.pushed_at || project.updatedAt
		};
	} catch {
		return project;
	}
}

function createProjectsStore() {
	let projects = $state<Project[]>(sortProjects(baseProjects));

	async function fetchUpdates() {
		if (!browser) return;

		const lastCheck = localStorage.getItem(LOCAL_STORAGE_LAST_CHECK_KEY);
		const shouldFetch =
			!lastCheck || new Date().getTime() - new Date(lastCheck).getTime() > ONE_HOUR_IN_MS;

		if (!shouldFetch) {
			const cached = localStorage.getItem(LOCAL_STORAGE_PROJECTS_KEY);
			if (cached) {
				try {
					projects = JSON.parse(cached);
					return;
				} catch {
					// Continue to fetch if cache is invalid
				}
			}
		}

		const updatedProjects = await Promise.all(baseProjects.map(fetchProjectUpdate));
		projects = sortProjects(updatedProjects);

		localStorage.setItem(LOCAL_STORAGE_LAST_CHECK_KEY, new Date().toISOString());
		localStorage.setItem(LOCAL_STORAGE_PROJECTS_KEY, JSON.stringify(projects));
	}

	if (browser) {
		fetchUpdates();
	}

	return {
		get list() {
			return projects;
		}
	};
}

export const projectsStore = createProjectsStore();
