export interface Project {
	title: string;
	description: string;
	url: string;
	repo?: string;
	updatedAt?: string;
	theme?: string;
	images?: string[];
}

export const projects: Project[] = [
	{
		title: 'Chromabox',
		description: 'A color palette generator for designers and developers',
		url: 'https://chromabox.fernando.is',
		repo: 'fmaclen/chromabox',
		theme: 'chromabox',
		images: ['chromabox-app.png', 'chromabox-website.png']
	},
	{
		title: 'fernando.is',
		description: 'This very website',
		url: 'https://fernando.is',
		repo: 'fmaclen/fernando.is',
		theme: 'fernando-is'
	},
	{
		title: 'Hollama',
		description: 'A minimal web-UI for talking to Ollama servers',
		url: 'https://hollama.fernando.is',
		repo: 'fmaclen/hollama',
		theme: 'hollama',
		images: ['hollama-session.png', 'hollama-settings.png', 'hollama-session-new.png']
	},
	{
		title: 'Canutin',
		description: 'A personal finance application for macOS, Windows & Linux',
		url: 'https://canutin.com',
		repo: 'fmaclen/canutin-desktop',
		theme: 'canutin',
		images: [
			'canutin-dashboard.png',
			'canutin-balance-sheet.png',
			'canutin-data.png',
			'canutin-trends.png',
			'canutin-transactions.png',
			'canutin-dashboard-dark.png'
		]
	},
	{
		title: 'svelte-currency-input',
		description:
			'A masked form input that converts numbers to localized currency formats as you type',
		url: 'https://npmjs.com/package/@canutin/svelte-currency-input',
		repo: 'fmaclen/svelte-currency-input',
		theme: 'svelte-currency-input'
	},
	{
		title: 'Julia Sanfrancisco',
		description: 'A web-based detective game largely generated by AI',
		url: 'https://julia.fernando.is',
		repo: 'fmaclen/julia-sanfrancisco',
		theme: 'julia-sanfrancisco',
		images: [
			'julia-sanfrancisco-splash.png',
			'julia-sanfrancisco-montreal.png',
			'julia-sanfrancisco-street-merchant.png',
			'julia-sanfrancisco-messenger.png',
			'julia-sanfrancisco-rome.png',
			'julia-sanfrancisco-singapore.png',
			'julia-sanfrancisco-baghdad.png',
			'julia-sanfrancisco-paris.png',
			'julia-sanfrancisco-stevedore.png',
			'julia-sanfrancisco-house-detective.png',
			'julia-sanfrancisco-headquarters.png'
		]
	},
	{
		title: 'auto-garden',
		description: 'Moisture monitor and irrigation system for my plants',
		url: 'https://github.com/fmaclen/auto-garden',
		repo: 'fmaclen/auto-garden',
		theme: 'auto-garden'
	},
	{
		title: 'Promptspree',
		description: 'Chat-based AI article generator and editor',
		url: 'https://promptspree.com',
		repo: 'fmaclen/promptspree',
		theme: 'promptspree',
		images: [
			'promptspree-homepage.png',
			'promptspree-article.png',
			'promptspree-footer.png',
			'promptspree-chat.png',
			'promptspree-completion.png'
		]
	},
	{
		title: 'rule-of-three',
		description: 'A tiny direct proportion calculator for macOS',
		url: 'https://github.com/fmaclen/rule-of-three',
		repo: 'fmaclen/rule-of-three',
		theme: 'rule-of-three',
		images: ['rule-of-three-default.png']
	},
	{
		title: 'Oak Hall',
		description: 'A historic family-run estate located in Northport, Maine',
		url: 'https://oakhallestate.org/',
		updatedAt: '2021-08-06T00:00:00Z',
		theme: 'oak-hall',
		images: [
			'oak-hall-cover.png',
			'oak-hall-library.png',
			'oak-hall-gardens.png',
			'oak-hall-footer.png'
		]
	},
	{
		title: 'Pantai.io',
		description:
			'Artificial intelligence applied to the creation of tools that improve the machine-human interface',
		url: 'https://pantai.io/',
		updatedAt: '2024-01-17T00:00:00Z',
		theme: 'pantai',
		images: ['pantai-homepage.png', 'pantai-legal.png', 'pantai-careers.png', 'pantai-about.png']
	},
	{
		title: 'Palfrey Press',
		description:
			'A specialist publisher producing authoritative books on obscure historical subjects, heraldry, oral histories, & other antiquarian matters',
		url: 'https://palfreypress.com',
		updatedAt: '2024-11-13T00:00:00Z',
		theme: 'palfrey-press',
		images: [
			'palfrey-press-homepage.png',
			'palfrey-press-about.png',
			'palfrey-press-card-3.png',
			'palfrey-press-card-1.png',
			'palfrey-press-card-2.png',
			'palfrey-press-card-4.png',
			'palfrey-press-catalog.png'
		]
	}
];
